version: '3'
services:
  default-table:
#local build
#    build: .
#get from repo
    image: {host+port}/web-editor:0.3"
    container_name: server-default-table
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "${EXT_PORT}:${INT_PORT}"
    command: ["run", "/backend/oper.py", "--server.maxMessageSize", "2048", "--server.maxUploadSize", "2048", "--server.port", "$INT_PORT"]